# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='age',
        ),
        migrations.RemoveField(
            model_name='website',
            name='children',
        ),
        migrations.RemoveField(
            model_name='website',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='website',
            name='income',
        ),
        migrations.RemoveField(
            model_name='website',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='website',
            name='location',
        ),
        migrations.RemoveField(
            model_name='website',
            name='relationship',
        ),
        migrations.AddField(
            model_name='through',
            name='age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cms.Age'),
        ),
        migrations.AddField(
            model_name='through',
            name='children',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cms.Children'),
        ),
        migrations.AddField(
            model_name='through',
            name='gender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cms.Gender'),
        ),
        migrations.AddField(
            model_name='through',
            name='income',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cms.Income'),
        ),
        migrations.AddField(
            model_name='through',
            name='industry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cms.Industry'),
        ),
        migrations.AddField(
            model_name='through',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cms.Location'),
        ),
        migrations.AddField(
            model_name='through',
            name='relationship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_cms.Relationship'),
        ),
    ]
