# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cms', '0003_auto_20161109_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='through',
            options={},
        ),
    ]
